namespace Core;

public class TestsCompiler
{
    private readonly string _testAttributeIdentifier = "Test";
    private readonly string _classAttributeIdentifier = "TestFixture";

    public CompilationUnitSyntax GenerateCodeByItem(GenerateItem item) =>
        SyntaxFactory
            .CompilationUnit()
            .WithMembers(
                SyntaxFactory.SingletonList<MemberDeclarationSyntax>(
                    item.NamespaceItem != null
                        ? GenerateNamespace(item)
                            .WithMembers(
                                SyntaxFactory.SingletonList<MemberDeclarationSyntax>(
                                    GenerateClass(item)
                                )
                            )
                        : GenerateClass(item)
                )
            )
            .NormalizeWhitespace();

    
    private FileScopedNamespaceDeclarationSyntax GenerateNamespace(GenerateItem item) =>
        SyntaxFactory.FileScopedNamespaceDeclaration(
            SyntaxFactory.IdentifierName($"{item.NamespaceName}.Tests")
        );

    private ClassDeclarationSyntax GenerateClass(GenerateItem item)
    {
        var list = new List<MemberDeclarationSyntax>();
        foreach (var method in item.Methods)
        {
            var name = item.GetMethodName(method);
            if (!string.IsNullOrEmpty(name))
                list.Add(GenerateTestMethod(name));
        }
        return SyntaxFactory
            .ClassDeclaration($"{item.ClassName}_Tests")
            .WithModifiers(GenerateModifier(SyntaxKind.PublicKeyword))
            .WithMembers(new SyntaxList<MemberDeclarationSyntax>(list))
            .WithAttributeLists(GenerateAttributeList(_classAttributeIdentifier));
    }

    private MemberDeclarationSyntax GenerateTestMethod(string name) =>
        SyntaxFactory
            .MethodDeclaration(
                SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)),
                GenerateIdentifier(name)
            )
            .WithAttributeLists(GenerateAttributeList(_testAttributeIdentifier))
            .WithModifiers(GenerateModifier(SyntaxKind.PublicKeyword))
            .WithBody(GenerateBlock());

    private SyntaxList<AttributeListSyntax> GenerateAttributeList(string identifier) =>
        SyntaxFactory.SingletonList<AttributeListSyntax>(
            SyntaxFactory.AttributeList(
                SyntaxFactory.SingletonSeparatedList<AttributeSyntax>(GenerateAttribute(identifier))
            )
        );

    private AttributeSyntax GenerateAttribute(string name) =>
        SyntaxFactory.Attribute(GenerateIdentifierName(name));

    private SyntaxTokenList GenerateModifier(SyntaxKind kind) =>
        SyntaxFactory.TokenList(SyntaxFactory.Token(kind));

    private SyntaxToken GenerateIdentifier(string identifier) =>
        SyntaxFactory.Identifier(identifier);

    private IdentifierNameSyntax GenerateIdentifierName(string identifier) =>
        SyntaxFactory.IdentifierName(identifier);

    private BlockSyntax GenerateBlock()
    {
        var argument = SyntaxFactory.Argument(
            SyntaxFactory.LiteralExpression(
                SyntaxKind.StringLiteralExpression,
                SyntaxFactory.Literal("autogenerated")
            )
        );

        var invocationExpression = SyntaxFactory.InvocationExpression(
            SyntaxFactory.MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                SyntaxFactory.IdentifierName("Assert"),
                SyntaxFactory.IdentifierName("Fail")
            )
        );

        var expression = SyntaxFactory.ExpressionStatement(
            invocationExpression.WithArgumentList(
                SyntaxFactory.ArgumentList(
                    SyntaxFactory.SingletonSeparatedList<ArgumentSyntax>(argument)
                )
            )
        );

        return SyntaxFactory.Block(expression);
    }

}