namespace Tests.Entities.Tests;
[TestFixture]
public class Foo_Tests
{
    [Test]
    public void SomeMethod1()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void SomeMethod2()
    {
        Assert.Fail("autogenerated");
    }
}